language: node_js
node_js:
  - "0.10"
  - "4.4.7"
before_install: npm i npm@latest -g

env:
  - RUN="npm run travis"
  - RUN="npm run test-shared-integration-tests"

matrix:
  fast_finish: true

script:
  - test/travis
